services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  midaas:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      - localstack
    ports:
      - "9999:8200"
    command: uvicorn --host 0.0.0.0 --port 8200 --reload main:app
  midaas_test:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - "MIDAAS_DYNAMODB_TABLE_NAME=midaas_bank_accounts__test"
    volumes:
      - ./:/app/
    depends_on:
      - localstack
    profiles:
      - testing
    command: pytest -vvvv
volumes:
  localstack:
